//Realizar o calculo de dois numeros inteiros e apresenta o valor entre eles....
#include<stdio.h>
#include<stdlib.h>
main(){
	int num1,num2, maior;
	//le o primeiro num...
	printf("Digite o primeiro numero:");
	scanf("%d", &num1);
	//lendo o segundo num....
	printf("Digite o segundo numero:");
	scanf("%d",&num2);
	//verificar o maior valor e aplica-la na variavel MAIOR....
	// usando o operador ternario...
	maior = num1 > num2 ? num1 : num2;
	//apresenta o maior entre as variaveis...
	printf("Maior=%d\n\n\n\n", maior);
	system("pause");	
}
